
// Thin wrapper around the Clocking Wizard IP "clk_wiz_mclk".
// The IP is generated by synth.tcl before synthesis.
module i2s_clkgen (
    input  logic clk,       // 100 MHz board clock
    input  logic rst_n,
    output logic mclk,      // 12.288 MHz master clock (from Clocking Wizard)
    output logic locked
);

    clk_wiz_mclk u_clk_wiz (
        .clk_in1  (clk),
        .resetn   (rst_n),
        .clk_out1 (mclk),
        .locked   (locked)
    );

endmodule

