
// =====================================================================
// iir_hpf1 — first-order IIR high-pass + asymmetric bias-shift tracker
//
//   Primary path:
//     y_hpf[n] = α · (y_hpf[n−1] + x[n] − x[n−1])
//
//   Asymmetric DC-tracking (Gap 1 of the realism plan):
//     x_pos[n] = max(x[n], 0)
//     γ_sel    = (x_pos[n] > env[n−1]) ? γ_atk : γ_rel
//     env[n]   = env[n−1] + γ_sel · (x_pos[n] − env[n−1])  // 1-pole LPF
//     y_out[n] = y_hpf[n] − env[n]                         // "bias shift"
//
//   This models the coupling-cap bias-shift that the DOWNSTREAM stage's
//   grid-diode pumps onto its grid leak under hard drive — the "blocking
//   distortion" / "CF squish" that a pure linear HPF cannot produce.
//   Physical kinetics: the grid diode conducts on positive swings and
//   charges the coupling cap fast (a few ms); after the peak the cap
//   discharges slowly through the grid-leak alone (hundreds of ms).  We
//   select γ_atk when the input is climbing above the current envelope
//   (cap charging) and γ_rel otherwise (cap discharging), so blocking
//   lands AT the pick attack and recovers naturally over the note body.
//   γ_atk = γ_rel (symmetric) is still valid — set them equal at gen time
//   to fall back to the old behaviour; γ_atk = γ_rel = 0 in the .mem file
//   cleanly disables the feature (used on the OT primary HPF).
//
//   Coefficient file layout (3 × 32-bit Q1.31 signed, hex):
//     Addr 0 : α        (HPF pole)
//     Addr 1 : γ_atk    (bias tracker — attack / cap charge through diode)
//     Addr 2 : γ_rel    (bias tracker — release / grid-leak discharge)
//   Generated by scripts/gen_triode_lut.py:write_hpf_mem
//   and scripts/gen_pentode_lut.py:write_hpf_mem.
//   x, y interface is sample_t (Q1.23 s24).
//   State y_prev is Q9.39 (48-bit signed) so the cascade doesn't truncate
//   LSB-level AC information every sample; env shares the same width.
//
//   Because the asymmetric tracker uses γ_atk (fast) on rising edges, env
//   follows the PEAK of x_pos rather than its mean (~A for a full-drive
//   sine instead of A/π).  SHIFT_BIAS scales the subtract to compensate;
//   the default (=5) yields ~3–5% peak subtract per stage at full drive,
//   matching the canonical ~5–10% cascade-total blocking of a real 2203.
//
//   Pipeline (5 register stages; env path runs in parallel with the α
//   multiply, same latency, so output subtract happens at S3):
//     S0 — on x_valid: compute diff = x[n] − x[n−1], acc_q39 = y_prev_q39
//          + (diff aligned to Q9.39); register acc_q39 and s0_x_lat.
//          ALSO rectify x → x_pos, subtract env_q39, register the 48-bit
//          s0_env_diff_q39 (the env subtract moved forward from S1 so the
//          S1 DSP multiplier sees a registered input — the old layout
//          chained the 48-bit sub and the γ multiplier in one cycle).
//     S1 — prod = α · acc_q39 (Q1.31 × Q9.39 → Q9.70).  Register
//          s1_prod80; pipeline s0_x_lat.
//          ALSO prod_γ = γ · s0_env_diff_q39; register s1_env_prod80.
//     S2 — y_q39_next = round_conv96(s1_prod80, 31)[47:0].  Register;
//          pipeline s1_x_lat.
//          ALSO env_delta_q39 = round_conv96(s1_env_prod80, 31)[47:0];
//          register s2_env_delta.
//     S3 — y_adj_q39 = s2_y_q39 − (env_q39 >>> SHIFT_BIAS) against the
//          pre-update env.  Register s3_y_adj_q39 (48-bit).  Update
//          x_prev, y_prev_q39, env_q39 ← env_q39 + s2_env_delta here
//          (the state updates read env_q39 pre-update, matching the
//          subtract's env snapshot).
//     S4 — narrow s3_y_adj_q39 → Q1.23 via round >>> 16, saturate s24,
//          register y_out.  Split from S3 to break the 48-bit subtract +
//          96-bit round-add + saturation compares out of a single cycle.
//
//   Coefficient file layout
//   ─────────────────────────
//     2 entries × 32-bit hex (Q1.31 signed two's complement).
//     Addr 0 : α (HPF pole)
//     Addr 1 : γ (bias tracker pole)
//     Generated by scripts/gen_triode_lut.py:write_hpf_mem.
// =====================================================================
module iir_hpf1
    import jcm800_pkg::*;
#(
    parameter string COEFF_FILE = "",
    // Gap 1 scale: with asymmetric γ_atk / γ_rel (see module header) env
    // tracks the PEAK of x_pos rather than its mean, so the un-scaled
    // subtract is ~A at full-scale drive.  SHIFT_BIAS right-shifts env
    // before subtraction to pull the per-stage blocking depth down into
    // the 3–6 % range canonical for a 2203:
    //   3 → ~12 % peak-subtract  (cascade-silencing with fast tracker)
    //   5 → ~3 % peak-subtract   (default; ~15 % cascade total, ~100 ms
    //                              peak-latency down from 250 ms symmetric)
    //   6 → ~1.5 % peak-subtract (mild; leaves sag dominant at m220)
    //   ∞ → feature off          (γ_atk = γ_rel = 0 in .mem also disables)
    parameter int unsigned SHIFT_BIAS = 5
)(
    input  logic    clk,
    input  logic    rst_n,
    input  sample_t x_in,
    input  logic    x_valid,
    output sample_t y_out,
    output logic    y_valid
);

    // ----------------------------------------------------------------
    // Coefficient ROM — Q1.31 α (addr 0), γ_atk (addr 1), γ_rel (addr 2)
    // ----------------------------------------------------------------
    (* rom_style = "distributed" *)
    logic [31:0] coef_mem [0:2];
    initial $readmemh(COEFF_FILE, coef_mem);

    wire signed [31:0] alpha_q31     = $signed(coef_mem[0]);
    wire signed [31:0] gamma_atk_q31 = $signed(coef_mem[1]);
    wire signed [31:0] gamma_rel_q31 = $signed(coef_mem[2]);

    // ----------------------------------------------------------------
    // State
    // ----------------------------------------------------------------
    sample_t             x_prev;
    logic signed [47:0]  y_prev_q39;
    logic signed [47:0]  env_q39;       // bias-tracker envelope (Gap 1)

    // ----------------------------------------------------------------
    // Rectify input to x_pos = max(x_in, 0) — proxy for downstream
    // grid-diode current that would charge-pump the coupling cap.
    // ----------------------------------------------------------------
    sample_t x_pos_c;
    always_comb begin
        x_pos_c = x_in[23] ? 24'sh000000 : x_in;
    end

    // ----------------------------------------------------------------
    // S0 — latch x, compute acc_q39 = y_prev_q39 + (diff << 16);
    //      also widen x_pos to Q9.39 and pre-subtract env_q39 for the
    //      bias tracker, so S1's γ multiplier gets a registered input.
    // ----------------------------------------------------------------
    sample_t             s0_x_lat;
    logic signed [47:0]  s0_acc_q39;
    logic signed [47:0]  s0_env_diff_q39;
    logic                s0_is_attack;
    logic                s0_valid;

    logic signed [24:0]  diff_c;
    logic signed [47:0]  diff_q39_c;
    logic signed [47:0]  acc_c;
    logic signed [47:0]  x_pos_q39_c;
    logic signed [47:0]  env_diff_c;
    logic                is_attack_c;

    always_comb begin
        diff_c      = $signed({x_in[23], x_in}) - $signed({x_prev[23], x_prev});
        diff_q39_c  = {{7{diff_c[24]}}, diff_c, 16'b0};   // s25 << 16 → 48b Q9.39
        acc_c       = y_prev_q39 + diff_q39_c;
        x_pos_q39_c = {{8{x_pos_c[23]}}, x_pos_c, 16'b0};  // s24 << 16 → 48b Q9.39
        env_diff_c  = x_pos_q39_c - env_q39;
        // x_pos_q39 > env_q39  ⇔ env_diff_c is positive (and non-zero).
        // env_diff_c's sign is its MSB; use !negative so env_diff_c == 0
        // falls into "release" (no attack selection required on idle).
        is_attack_c = !env_diff_c[47] && (env_diff_c != 48'sd0);
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            s0_x_lat        <= '0;
            s0_acc_q39      <= '0;
            s0_env_diff_q39 <= '0;
            s0_is_attack    <= 1'b0;
            s0_valid        <= 1'b0;
        end else begin
            s0_valid <= x_valid;
            if (x_valid) begin
                s0_x_lat        <= x_in;
                s0_acc_q39      <= acc_c;
                s0_env_diff_q39 <= env_diff_c;
                s0_is_attack    <= is_attack_c;
            end
        end
    end

    // ----------------------------------------------------------------
    // S1 — α·acc_q39 (HPF path); γ·env_diff (bias path).  Both DSP
    //      multiplies run in parallel on registered inputs.  x_lat
    //      pipelined through.
    // ----------------------------------------------------------------
    logic signed [79:0]  prod80_c;
    logic signed [79:0]  env_prod80_c;

    logic signed [79:0]  s1_prod80;
    logic signed [79:0]  s1_env_prod80;
    sample_t             s1_x_lat;
    logic                s1_valid;

    logic signed [31:0] gamma_sel_q31;
    assign gamma_sel_q31 = s0_is_attack ? gamma_atk_q31 : gamma_rel_q31;

    always_comb begin
        prod80_c     = alpha_q31     * s0_acc_q39;
        env_prod80_c = gamma_sel_q31 * s0_env_diff_q39;
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            s1_prod80     <= '0;
            s1_env_prod80 <= '0;
            s1_x_lat      <= '0;
            s1_valid      <= 1'b0;
        end else begin
            s1_valid <= s0_valid;
            if (s0_valid) begin
                s1_prod80     <= prod80_c;
                s1_env_prod80 <= env_prod80_c;
                s1_x_lat      <= s0_x_lat;
            end
        end
    end

    // ----------------------------------------------------------------
    // S2 — round prod → Q9.39 y_q39_next; round env_prod → env_delta_q39.
    // ----------------------------------------------------------------
    logic signed [95:0]  prod80_ext;
    logic signed [95:0]  y_q39_96;
    logic signed [47:0]  y_q39_next_c;
    logic signed [95:0]  env_prod80_ext;
    logic signed [95:0]  env_delta_96;
    logic signed [47:0]  env_delta_q39_c;

    logic signed [47:0]  s2_y_q39;
    logic signed [47:0]  s2_env_delta_q39;
    sample_t             s2_x_lat;
    logic                s2_valid;

    always_comb begin
        prod80_ext      = {{16{s1_prod80[79]}},     s1_prod80};
        y_q39_96        = round_conv96(prod80_ext, 31);
        y_q39_next_c    = y_q39_96[47:0];
        env_prod80_ext  = {{16{s1_env_prod80[79]}}, s1_env_prod80};
        env_delta_96    = round_conv96(env_prod80_ext, 31);
        env_delta_q39_c = env_delta_96[47:0];
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            s2_y_q39         <= '0;
            s2_env_delta_q39 <= '0;
            s2_x_lat         <= '0;
            s2_valid         <= 1'b0;
        end else begin
            s2_valid <= s1_valid;
            if (s1_valid) begin
                s2_y_q39         <= y_q39_next_c;
                s2_env_delta_q39 <= env_delta_q39_c;
                s2_x_lat         <= s1_x_lat;
            end
        end
    end

    // ----------------------------------------------------------------
    // S3 — subtract env (pre-update) from HPF output; register the wide
    //      y_adj_q39 only.  Round + saturate + output register move to
    //      S4 so the single-cycle carry chain (48-bit sub → 96-bit round
    //      add → saturation compares) gets split in half for timing.
    //      State updates (x_prev, y_prev_q39, env_q39) happen here; they
    //      read env_q39 pre-update, matching the subtract's env snapshot.
    // ----------------------------------------------------------------
    logic signed [47:0]  env_scaled_q39;
    logic signed [47:0]  y_adj_q39_c;

    logic signed [47:0]  s3_y_adj_q39;
    logic                s3_valid;

    always_comb begin
        // Scale env down before subtracting — see SHIFT_BIAS rationale above.
        env_scaled_q39 = env_q39 >>> SHIFT_BIAS;
        y_adj_q39_c    = s2_y_q39 - env_scaled_q39;
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            x_prev       <= '0;
            y_prev_q39   <= '0;
            env_q39      <= '0;
            s3_y_adj_q39 <= '0;
            s3_valid     <= 1'b0;
        end else begin
            s3_valid <= s2_valid;
            if (s2_valid) begin
                s3_y_adj_q39 <= y_adj_q39_c;
                x_prev       <= s2_x_lat;
                y_prev_q39   <= s2_y_q39;
                env_q39      <= env_q39 + s2_env_delta_q39;
            end
        end
    end

    // ----------------------------------------------------------------
    // S4a — round s3_y_adj_q39 >>> 16 → Q1.23; register the 96-bit
    //       rounded value.  S4b does the saturating narrow on the next
    //       cycle so the 96-bit bias-add and the 96-bit saturation
    //       compare do not share a single sys_clk period.
    // ----------------------------------------------------------------
    logic signed [95:0]  y_adj_ext;
    logic signed [95:0]  y_q23_96_c;
    logic signed [95:0]  y_q23_96_q;
    logic                s4_valid;

    always_comb begin
        y_adj_ext  = {{48{s3_y_adj_q39[47]}}, s3_y_adj_q39};
        y_q23_96_c = round_conv96(y_adj_ext, 16);
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            y_q23_96_q <= '0;
            s4_valid   <= 1'b0;
        end else begin
            s4_valid <= s3_valid;
            if (s3_valid) y_q23_96_q <= y_q23_96_c;
        end
    end

    // ----------------------------------------------------------------
    // S4b — saturate rounded value to sample_t.
    // ----------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            y_out   <= '0;
            y_valid <= 1'b0;
        end else begin
            y_valid <= s4_valid;
            if (s4_valid) y_out <= saturate_s24(y_q23_96_q);
        end
    end

endmodule
