
// =====================================================================
// input_scale — fixed Q16.16 multiply on the ADC sample stream
//
//   y = saturate_s24( round( (x · SCALE_Q16_16) >>> 16 ) )
//
//   Sits at the very front of the DSP chain to keep V1A's LUT inside
//   its small-signal region for typical guitar levels.  V1A bakes the
//   tube's voltage gain (Gss ≈ 41.5) into the LUT slope, so the soft-
//   rail knee (h ≈ 0.92) is reached at LUT input ≈ −33 dBFS.  Without
//   pre-attenuation a normal guitar signal lands V1A in permanent
//   saturation upstream of the gain pot — the "gain control sounds
//   like a volume" symptom.
//
//   The default scale comes from jcm800_lut_pkg::INPUT_SCALE_DEFAULT_Q16_16,
//   regenerated by scripts/gen_triode_lut.py alongside the LUTs (so a
//   future Koren-model recalibration that changes V1A's headroom will
//   propagate without manual edits here).
// =====================================================================
module input_scale
    import jcm800_pkg::*;
    import jcm800_lut_pkg::*;
(
    input  logic    clk,
    input  logic    rst_n,
    input  sample_t x_in,
    input  logic    x_valid,
    output sample_t y_out,
    output logic    y_valid
);

    // Q1.23 × Q16.16 → Q17.39 (56-bit signed)
    logic signed [55:0] prod_c;
    logic signed [55:0] prod_q;
    logic               s0_valid;

    always_comb begin
        prod_c = $signed(x_in) * $signed(INPUT_SCALE_DEFAULT_Q16_16);
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            prod_q   <= '0;
            s0_valid <= 1'b0;
        end else begin
            s0_valid <= x_valid;
            if (x_valid) prod_q <= prod_c;
        end
    end

    // Convergent round >>> 16 → Q1.23, then saturate.
    logic signed [95:0] prod_ext;
    logic signed [95:0] prod_rounded;

    always_comb begin
        prod_ext     = {{40{prod_q[55]}}, prod_q};
        prod_rounded = round_conv96(prod_ext, 16);
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            y_out   <= '0;
            y_valid <= 1'b0;
        end else begin
            y_valid <= s0_valid;
            if (s0_valid) y_out <= saturate_s24(prod_rounded);
        end
    end

endmodule
