
// =====================================================================
// screen_supply — shared EL34 screen-grid RC state
//
//   Simulates the 1 kΩ screen stopper + 47 µF bypass cap that sits
//   between B+ and the push-pull pair's g2 pins in the JCM800 2203.
//   When both tubes draw heavy screen current (Ig2_sum), the cap
//   discharges faster than it can be refilled through the stopper,
//   Vg2 droops, and the tubes lose gain/headroom — the "brown" sag
//   character that open-loop power-amp models miss.
//
//   Discrete update at the oversampled rate fs = 768 kHz:
//
//       Δ_up = α · (NOM − vg2_state)          // recovery toward B+
//       Δ_dn = β · ig2_sum                    // drain from both g2s
//       vg2_state[n+1] = vg2_state[n] + Δ_up − Δ_dn
//
//   α and β are Q1.31 "very small" coefficients baked by
//   scripts/gen_pentode_lut.py from R_SCREEN·C_SCREEN and the chosen
//   peak-current normalisation (see PEAK_IG2_A in the generator).
//
//   State is kept as a 32-bit signed Q2.30 word (nom = 0x4000_0000 =
//   1.0) so the tiny α and β updates don't get lost in a narrower
//   accumulator.  The output to pentode_stage.sv is the top 16 bits
//   in Q2.14 format (nom = 0x4000), good enough for the slow-envelope
//   signal the pentode multiplier needs.
//
//   Latency: 3 cycles from ig2_sum_valid to state_q2_30 update
//            (input latch → multiply → delta+state accumulate).  The
//            integrator only advances once per 768 kHz oversampled
//            sample (≈ 130 sys_clk cycles), so a 3-cycle pipeline is
//            invisible to the slow-envelope response and breaks the
//            long carry chain that was failing setup on sys_clk.
// =====================================================================
module screen_supply
    import jcm800_pkg::*;
    import jcm800_power_pkg::*;
(
    input  logic                clk,
    input  logic                rst_n,

    // Sum of per-tube |ip| · IG2_RATIO estimates (Q1.23 signed, but always
    // ≥ 0 in practice).  Generated by the |·|-scale path inside each
    // pentode_stage.  Width is 25 bits so two Q1.23 values can sum without
    // overflow before entering this module.
    input  logic signed [24:0]  ig2_sum_q1_23,
    input  logic                ig2_sum_valid,

    // Slowly-varying screen ratio, Q2.14 signed (≥ 0 in practice).
    //   nom (Vg2 = Vg2_nom) → 16'h4000 (= 1.0)
    //   full sag           → ~16'h2000 (≈ 0.5) at worst
    output logic signed [15:0]  vg2_ratio_q2_14
);

    // --------------------------------------------------------------
    // State: Q2.30 signed (1.0 = 0x4000_0000).  Reset to nominal.
    // --------------------------------------------------------------
    logic signed [31:0] state_q2_30;

    localparam logic signed [31:0] STATE_NOM_Q2_30 = 32'sh40000000;

    // --------------------------------------------------------------
    // P1 — latch inputs and pre-compute err = NOM − state.
    //   Registering the 25-bit ig2 port here terminates the
    //   pentode_stage → screen_supply combinational path at a flop
    //   immediately inside this module.
    // --------------------------------------------------------------
    logic signed [31:0] err_q;
    logic signed [31:0] ig2_q2_30_q;
    logic               valid_d1;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            err_q       <= '0;
            ig2_q2_30_q <= '0;
            valid_d1    <= 1'b0;
        end else begin
            err_q       <= STATE_NOM_Q2_30 - state_q2_30;
            // 25-bit Q1.23 signed << 7 → 32-bit Q2.30 signed.
            ig2_q2_30_q <= {ig2_sum_q1_23, 7'b0};
            valid_d1    <= ig2_sum_valid;
        end
    end

    // --------------------------------------------------------------
    // P2 — two DSP multiplies (Q1.31 · Q2.30 → Q3.61).  Registering
    //   the products lets the synthesiser use the DSP48E1 P register.
    // --------------------------------------------------------------
    logic signed [63:0] prod_up_q;
    logic signed [63:0] prod_dn_q;
    logic               valid_d2;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            prod_up_q <= '0;
            prod_dn_q <= '0;
            valid_d2  <= 1'b0;
        end else begin
            prod_up_q <= $signed(SCREEN_ALPHA_Q1_31) * err_q;
            prod_dn_q <= $signed(SCREEN_BETA_Q1_31)  * ig2_q2_30_q;
            valid_d2  <= valid_d1;
        end
    end

    // --------------------------------------------------------------
    // P3 — shift back to Q2.30 and apply the state update.  The two
    //   deltas are signed 32-bit values ≤ α (β) in magnitude, so the
    //   final add/subtract is just a 32-bit accumulate.
    // --------------------------------------------------------------
    logic signed [31:0] delta_up_c;
    logic signed [31:0] delta_dn_c;

    always_comb begin
        delta_up_c = prod_up_q >>> 31;
        delta_dn_c = prod_dn_q >>> 31;
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state_q2_30 <= STATE_NOM_Q2_30;
        end else if (valid_d2) begin
            state_q2_30 <= state_q2_30 + delta_up_c - delta_dn_c;
        end
    end

    // --------------------------------------------------------------
    // Output: Q2.30 → Q2.14 via top-16-bit slice (implicit round-down
    // is fine for this slow-envelope signal).
    // --------------------------------------------------------------
    assign vg2_ratio_q2_14 = state_q2_30[31:16];

endmodule
