
// =====================================================================
// tonestack — 3-band passive tone stack (Marshall TMB-style)
//
//   Sits between u_preamp (post-gain) and u_master in the 2203 signal
//   chain.  Three 1st-order shelving biquads in series, coefficients
//   looked up from a pot-indexed 3D ROM on every sample.
//
//   Signal flow (sample_t Q1.23 s24 at 768 kHz):
//
//     x_in ──► sec1 (LF shelf) ──► sec2 (MF shelf) ──► sec3 (HF shelf) ──► y_out
//                ▲                    ▲                    ▲
//                │                    │                    │
//         ┌──────┴──────────┬─────────┴─────────┬──────────┴──────────┐
//         │                 │                   │                     │
//         │      coef_mem[grid_addr] — 9 × Q3.29 coefficients          │
//         │        addressed by {bass[7:5], mid[7:5], treble[7:5]}     │
//         └────────────────────────────────────────────────────────────┘
//
//   Pot grid
//   ────────
//     8 × 8 × 8 = 512 pot triples.  Each pot is 8-bit at the UART
//     interface; the ROM is addressed by the top 3 bits (one grid cell
//     per 32 pot steps).  That's coarse enough to see on a spectrum
//     analyser as stair-stepping, but audibly acceptable for v1.  A
//     later pass will add trilinear interpolation without touching the
//     .mem or the biquad pipeline — only the address-side lookup.
//
//   Coefficient ROM layout
//   ──────────────────────
//     512 entries × 9 × 32-bit Q3.29 signed, loaded from
//     lut_out/tonestack_coefs.mem (generated by
//     scripts/gen_tonestack_lut.py).  Coefficient order within one
//     entry (addr-offsets 0..8):
//         0: sec1_b0   1: sec1_b1   2: sec1_a1      (LF shelf)
//         3: sec2_b0   4: sec2_b1   5: sec2_a1      (MF shelf)
//         6: sec3_b0   7: sec3_b1   8: sec3_a1      (HF shelf)
//     $readmemh on the 2D unpacked array fills row-major, so line N of
//     the .mem lands at coef_mem[N / 9][N % 9].
//
//   Pipeline
//   ────────
//     Three biquad_coef_ports instances in series, each a 4-cycle
//     pipeline matching cathode_shelf.sv.  Total latency ≈ 12 sys_clk
//     cycles from x_valid to y_valid.  Trivial against the
//     ~130-cycle/sample budget at 768 kHz.
//
//     Coefficients are latched once on x_valid and held stable for the
//     duration of the entire 3-section pipeline.  The next sample's
//     x_valid doesn't arrive for another ~130 cycles, well after
//     section 3 has emitted y_valid, so there's no coef-pipeline
//     overlap to worry about.
// =====================================================================
module tonestack
    import jcm800_pkg::*;
#(
    parameter string COEF_FILE = "tonestack_coefs.mem"
)(
    input  logic        clk,
    input  logic        rst_n,
    input  sample_t     x_in,
    input  logic        x_valid,
    input  logic [7:0]  bass_pot_pos,
    input  logic [7:0]  mid_pot_pos,
    input  logic [7:0]  treble_pot_pos,
    output sample_t     y_out,
    output logic        y_valid
);

    // ----------------------------------------------------------------
    // Coefficient ROM — 512 × 9 × 32-bit Q3.29.
    //
    // Let Vivado choose block vs. distributed ROM based on size — at
    // 147 kbit it'll typically pack into 4-5 BRAM36 blocks.
    // ----------------------------------------------------------------
    localparam int GRID      = 8;
    localparam int N_ENTRIES = GRID * GRID * GRID;   // 512
    localparam int N_COEFS   = 9;

    logic [31:0] coef_mem [0:N_ENTRIES-1][0:N_COEFS-1];
    initial $readmemh(COEF_FILE, coef_mem);

    // ----------------------------------------------------------------
    // Grid-address lookup — top 3 bits of each 8-bit pot form a 9-bit
    // flat address.  Bass is the most-significant field so adjacent
    // treble values map to adjacent ROM addresses, giving the best
    // spatial locality for a future trilinear interpolator.
    // ----------------------------------------------------------------
    wire [2:0] bass_idx   = bass_pot_pos  [7:5];
    wire [2:0] mid_idx    = mid_pot_pos   [7:5];
    wire [2:0] treble_idx = treble_pot_pos[7:5];
    wire [8:0] grid_addr  = {bass_idx, mid_idx, treble_idx};

    // ----------------------------------------------------------------
    // Stage R0 — on x_valid, register the 9 coefficients for the
    // current pot triple and pass x_in straight through to section 1.
    // The biquad's own S0 then picks up x_in and the registered coefs
    // on the same cycle (R0 and S0 are the same register bank from
    // section 1's perspective; naming separates the coef lookup from
    // the biquad arithmetic).
    // ----------------------------------------------------------------
    logic signed [31:0]  sec1_b0, sec1_b1, sec1_a1;
    logic signed [31:0]  sec2_b0, sec2_b1, sec2_a1;
    logic signed [31:0]  sec3_b0, sec3_b1, sec3_a1;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sec1_b0 <= '0; sec1_b1 <= '0; sec1_a1 <= '0;
            sec2_b0 <= '0; sec2_b1 <= '0; sec2_a1 <= '0;
            sec3_b0 <= '0; sec3_b1 <= '0; sec3_a1 <= '0;
        end else if (x_valid) begin
            sec1_b0 <= $signed(coef_mem[grid_addr][0]);
            sec1_b1 <= $signed(coef_mem[grid_addr][1]);
            sec1_a1 <= $signed(coef_mem[grid_addr][2]);
            sec2_b0 <= $signed(coef_mem[grid_addr][3]);
            sec2_b1 <= $signed(coef_mem[grid_addr][4]);
            sec2_a1 <= $signed(coef_mem[grid_addr][5]);
            sec3_b0 <= $signed(coef_mem[grid_addr][6]);
            sec3_b1 <= $signed(coef_mem[grid_addr][7]);
            sec3_a1 <= $signed(coef_mem[grid_addr][8]);
        end
    end

    // ----------------------------------------------------------------
    // Three cascaded biquad sections — each is a 4-cycle pipeline.
    // The coefs into each section are the registered sec{N}_* values
    // held stable for the duration of the pipeline.
    // ----------------------------------------------------------------
    sample_t y_sec1, y_sec2;
    logic    y_sec1_valid, y_sec2_valid;

    biquad_coef_ports u_sec1 (
        .clk     (clk),
        .rst_n   (rst_n),
        .b0_q29  (sec1_b0),
        .b1_q29  (sec1_b1),
        .a1_q29  (sec1_a1),
        .x_in    (x_in),
        .x_valid (x_valid),
        .y_out   (y_sec1),
        .y_valid (y_sec1_valid)
    );

    biquad_coef_ports u_sec2 (
        .clk     (clk),
        .rst_n   (rst_n),
        .b0_q29  (sec2_b0),
        .b1_q29  (sec2_b1),
        .a1_q29  (sec2_a1),
        .x_in    (y_sec1),
        .x_valid (y_sec1_valid),
        .y_out   (y_sec2),
        .y_valid (y_sec2_valid)
    );

    biquad_coef_ports u_sec3 (
        .clk     (clk),
        .rst_n   (rst_n),
        .b0_q29  (sec3_b0),
        .b1_q29  (sec3_b1),
        .a1_q29  (sec3_a1),
        .x_in    (y_sec2),
        .x_valid (y_sec2_valid),
        .y_out   (y_out),
        .y_valid (y_valid)
    );

endmodule
