
// =====================================================================
// triode_bram — 4097x24 dual-port read-only BRAM, $readmemh initialised
//
//   One BRAM holds either an h(x) transfer table or a PCHIP tangent
//   table generated by scripts/gen_triode_lut.py.  The depth is rounded
//   up to 8192 because Vivado infers RAMB36 SDP at >4096 entries; the
//   unused upper half is zeroed in the initial block so any out-of-range
//   read returns 0.
//
//   Both read ports are synchronous with a single-cycle latency and no
//   reset on the output register — async reset on the BRAM output reg
//   forces Vivado to fall back to distributed (LUT) RAM.
// =====================================================================
module triode_bram #(
    parameter string INIT_FILE = ""
)(
    input  logic                clk,
    input  logic [12:0]         addr_a,
    input  logic [12:0]         addr_b,
    output logic signed [23:0]  q_a,
    output logic signed [23:0]  q_b
);

    (* ram_style = "block" *)
    logic [23:0] mem [0:8191];

    initial begin
        for (int i = 0; i < 8192; i++) mem[i] = 24'h000000;
        $readmemh(INIT_FILE, mem, 0, 4096);
    end

    always_ff @(posedge clk) begin
        q_a <= $signed(mem[addr_a]);
        q_b <= $signed(mem[addr_b]);
    end

endmodule
