# =====================================================================
# lint.tcl — RTL elaboration-only syntax check (no synthesis mapping)
#
#   Usage: vivado -mode batch -source tcl/lint.tcl -tclargs <part> <rtl files...>
# =====================================================================

if {[llength $argv] < 2} {
    error "usage: lint.tcl <part> <rtl files...>"
}

set part     [lindex $argv 0]
set rtl_srcs [lrange $argv 1 end]

read_verilog -sv $rtl_srcs

# Stub for the Clocking Wizard IP — the real IP is generated by
# tcl/project.tcl, but lint runs without a project / IP generation.
set stub_path [file join [file dirname [info script]] .. build _lint_stubs.sv]
file mkdir [file dirname $stub_path]
set fh [open $stub_path "w"]
puts $fh "module clk_wiz_mclk(input clk_in1, input resetn, output clk_out1, output locked);"
puts $fh "    assign clk_out1 = 1'b0;"
puts $fh "    assign locked   = 1'b1;"
puts $fh "endmodule"
close $fh
read_verilog -sv $stub_path

# Make $readmemh("v1a_lut.mem", ...) resolvable during elaboration.
set mem_dir [file normalize [file join [file dirname [info script]] .. lut_out]]
set_property include_dirs $mem_dir [current_fileset]

synth_design -rtl -top arty_top -part $part
puts "Lint passed: elaborated arty_top on $part"

# Also elaborate each redesigned module standalone so it is checked before
# the integration step wires it into the top.  Each call covers the whole
# sub-hierarchy (gain_stage pulls in iir_lpf1, cathode_shelf, iir_hpf1,
# triode_bram, and both packages).
foreach top {gain_stage ir_cab tonestack ht_supply speaker_load} {
    synth_design -rtl -top $top -part $part
    puts "Lint passed: elaborated $top on $part"
}
